name: python-development

run-name: ${{ github.actor }} - ${{ github.ref_name }}


on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: 3.8

jobs:
  python-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src


    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: '${{ env.PYTHON_VERSION }}'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage
        pwd
        pip install -r requirements

    - name: Runs tests
      run: python manage.py test

    - name: Generate covarege
      run: coverage run manage.py test

    - name: Show coverage report
      run: coverage report

    - name: Checks code style
      run: |
        flake8 . --show-source --statistics
      continue-on-error: true

    - name: Checks the complexity of the code
      run: |
        flake8 --max-complexity=10 --statistics
      continue-on-error: true


    - name: Upload Python code as artifact
      uses: actions/upload-artifact@v4
      with:
          name: python-code
          path: ./src
